name: Release Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Setup git user
        run: |
          git config user.name "cd"
          git config user.email "cd@users.noreply.github.com"

      - name: Bump version & generate changelog
        run: npx --yes standard-version --release-as patch

      - name: Push changes
        run: |
          git push --follow-tags https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: pnpm build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
